### ISSUE TITLE
Player State

### ISSUE THREAD

**Issue by AdamJNew** [ShaunLWM/node-csgo-gsi#11]
Is there a way to check player health in this package?

**Comment by AdamJNew** [comment]
`
        if (typeof data["player"] !== "undefined") {
            this.emit("player", data["player"]);
            this.emit("playerHealth", data["player"]["state"]["health"]);
            this.emit("playerName", data["player"]["name"]);
        }`

Just need to add this into index.js of your package

**Comment by ShaunLWM** [comment]
Instead of nitpicking every single information, you can just listen for the `player` event and act accordingly 😊
