### ISSUE TITLE
Doesnt connect with csgo

### ISSUE THREAD

**Issue by Haxters** [ShaunLWM/node-csgo-gsi#8]
I've set up the whole code that you've provided, everything works, but it doesn't connect with csgo itself. Do you have any suggestions or links that may sort my issue out?

**Comment by ShaunLWM** [comment]
Apologies for the late reply. Has your problem been fixed?

**Comment by sergioprates** [comment]
Same error here. The csgo dont send requests to client

**Comment by sergioprates** [comment]
This works in csgo server cfg folder? My server not read the file gamestate_integration_node.cfg

**Comment by ShaunLWM** [comment]
Nope, this file will be in your personal game folder. Not server's.
